---
- hosts: server2
  remote_user: user500
  become: yes
  tasks:
     - name: Install httpd
       yum: name={{ item }} state=installed
       with_items:
             - httpd
             - telnet
             - curl
             - lynx
     - name: create index.html
       copy: src=index.html dest=/var/www/html
     - name: start httpd service
       service: name=httpd state=started
